### ISSUE TITLE
Unable to send mail via Gmail API with java code

### ISSUE THREAD

**Issue by MitulKapoor** [gsuitedevs/java-samples#53]
(Please fill out these details before submitting an issue)

### Sample Name
Gmail Quickstart

### Expected Behavior
Should be able to send email 

### Actual Behavior
com.google.api.client.googleapis.json.GoogleJsonResponseException: 403 Forbidden
{
  "code" : 403,
  "errors" : [ {
    "domain" : "global",
    "message" : "Insufficient Permission",
    "reason" : "insufficientPermissions"
  } ],
  "message" : "Insufficient Permission"
}

### Specifications
  - Java version (`java -version`)
  - OS (Mac/Linux/Windows)

**Comment by erickoledadevrel** [comment]
The quickstart only requests the Gmail labels scope:

https://github.com/gsuitedevs/java-samples/blob/master/gmail/quickstart/src/main/java/GmailQuickstart.java#L47

In order to send email you'll need to get a new token with a more permissive scope:

https://developers.google.com/gmail/api/auth/scopes#gmail_scopes
